'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GDev_Asset_Store_Tool.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Application_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Application_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;id&quot;: &quot;&quot;,
        '''  &quot;name&quot;: &quot;&quot;,
        '''  &quot;authors&quot;: [&quot;&quot;],
        '''  &quot;license&quot;: &quot;&quot;,
        '''  &quot;shortDescription&quot;: &quot;&quot;,
        '''  &quot;description&quot;: &quot;Enter a description. Leave the rest empty, it will be autogenerated&quot;,
        '''  &quot;previewImageUrls&quot;: [],
        '''  &quot;tags&quot;: [],
        '''  &quot;objectAssets&quot;: [
        '''    {
        '''      &quot;object&quot;: {},
        '''      &quot;resources&quot;: [ ],
        '''      &quot;customization&quot;: []
        '''    }
        '''  ],
        '''  &quot;gdevelopVersion&quot;: &quot;&quot;,
        '''  &quot;version&quot;: &quot;&quot;
        '''}.
        '''</summary>
        Friend ReadOnly Property asset_template() As String
            Get
                Return ResourceManager.GetString("asset_template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;id&quot;: &quot;&quot;,
        '''  &quot;name&quot;: &quot;&quot;,
        '''  &quot;authors&quot;: [&quot;&quot;],
        '''  &quot;license&quot;: &quot;&quot;,
        '''  &quot;shortDescription&quot;: &quot;&quot;,
        '''  &quot;description&quot;: &quot;Enter a description. Leave the rest empty, it will be autogenerated&quot;,
        '''  &quot;previewImageUrls&quot;: [],
        '''  &quot;tags&quot;: [],
        '''  &quot;objectAssets&quot;: [
        '''    {
        '''      &quot;object&quot;: {&quot;name&quot;: &quot;NewBBText&quot;,
        '''          &quot;tags&quot;: &quot;&quot;,
        '''          &quot;type&quot;: &quot;BBText::BBText&quot;,
        '''          &quot;variables&quot;: [],
        '''          &quot;effects&quot;: [],
        '''          &quot;behaviors&quot;: [],
        '''          &quot;content&quot;: {
        '''            &quot;text&quot;: &quot;[b]bold[/b] [i]italic[/i] [size [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property bbtextobject_template() As String
            Get
                Return ResourceManager.GetString("bbtextobject_template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property bitmaptext_template() As String
            Get
                Return ResourceManager.GetString("bitmaptext_template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Close_Grey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close_Grey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Close_Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close_Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Metadata() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Metadata", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Minimize_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Minimize_Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Minimize_Grey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Minimize_Grey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Replay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Replay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SelectionArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectionArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stopwatch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stopwatch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;id&quot;: &quot;&quot;,
        '''  &quot;name&quot;: &quot;&quot;,
        '''  &quot;authors&quot;: [&quot;&quot;],
        '''  &quot;license&quot;: &quot;&quot;,
        '''  &quot;shortDescription&quot;: &quot;&quot;,
        '''  &quot;description&quot;: &quot;Enter a description. Leave the rest empty, it will be autogenerated&quot;,
        '''  &quot;previewImageUrls&quot;: [],
        '''  &quot;tags&quot;: [],
        '''  &quot;objectAssets&quot;: [
        '''    {
        '''      &quot;object&quot;: {
        '''        &quot;bold&quot;: false,
        '''        &quot;italic&quot;: false,
        '''        &quot;name&quot;: &quot;NewText&quot;,
        '''        &quot;smoothed&quot;: true,
        '''        &quot;tags&quot;: &quot;&quot;,
        '''        &quot;type&quot;: &quot;TextObject::Text&quot;,
        '''        &quot;underlined&quot;: false,
        '''        &quot;variables&quot;: [],
        '''        &quot;effects&quot;:  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property textobject_template() As String
            Get
                Return ResourceManager.GetString("textobject_template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
